language: python
matrix:
    include:
    - python: "3.4"
      env: DEPS="numpy scipy nose matplotlib pytables cython beautiful-soup pandas"
    - python: "3.3"
      env: DEPS="numpy scipy nose matplotlib pytables cython beautiful-soup pandas"
    - python: "2.7"
      env: DEPS="numpy scipy nose matplotlib pytables cython beautiful-soup pandas"

# setup adapted from https://github.com/soft-matter/trackpy/blob/master/.travis.yml
before_install:
    - sudo apt-get update
    - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh; fi
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - export PATH=/home/travis/miniconda3/bin:$PATH
    # See:
    # https://groups.google.com/a/continuum.io/forum/#!topic/conda/RSFENqovnro
    - conda update --yes --no-deps conda
    # Learned the hard way: miniconda is not always up-to-date with conda.
    - conda update --yes conda

# command to install dependencies
install: 
    - sudo apt-get install gsl-bin libgsl0-dev libgsl0ldbl libhdf5-serial-dev hdf5-tools
    - conda install --yes -c conda conda-env
#    - conda create -n testenv --yes $DEPS pip python=${TRAVIS_PYTHON_VERSION}
#    - source activate testenv
    - conda install --yes $DEPS pip python=${TRAVIS_PYTHON_VERSION}
    - pip install coveralls 
#    - pip install mechanize
    - git clone https://github.com/rth/opacplot2 --branch=master --single-branch
    - cd opacplot2/
# so we can use the cythoned files without installing them
#    - python setup.py build_ext --inplace -f -v
    - python setup.py install
    - cd ..
    - rm -rf opacplot2/
    - python setup.py develop
    - pwd
    - ls -R
#- cd ./hedp/tests/


# command to run tests
script: 
    - python ./hedp/tests/run.py --with-coverage --cover-package=hedp
    - coverage run --source=hedp ./hedp/tests/run.py

after_success:
    coveralls

